@echo off
rem generated by builder.pl: configures for building with MSVC
if exist clean.bat del clean.bat
if exist makefile.* del makefile.*
if exist watmake.bat del watmake.bat
if exist msvcmake.bat del msvcmake.bat
if exist multitet.dsp del multitet.dsp
copy build\msvcmake.bat
copy build\clean.bat
copy build\multitet.dsp
utod .../*.c .../*.h
echo Ready for building with MSVC -- type:
echo   'msvcmake' for a release build
echo   'clean' to tidy up
echo or just run the project file multitet.dsp
