#!/bin/sh
# generated by builder.pl: configures for building in Unix
rm -f makefile makefile.* clean.bat watmake.bat msvcmake.bat *.dsp
cp -f build/makefile.uni makefile
cp -f build/makefile.all .
find . -name *.c -o -name *.h -exec sh -c 'tmpfile=/tmp/.dtou.$$;
	tr -d \\r < {} > $tmpfile &&
	touch -r {} $tmpfile &&
	mv $tmpfile {}' \;
echo "Ready for building in Unix -- type:"
echo "  'make' for a release build"
echo "  'make debug' for a debugging build"
echo "  'make clean' to tidy up"
