# generated by builder.pl: makefile for Unix

CC = gcc
EXE =
RELEASE_CFLAGS = -Wall -m486 -O3 -ffast-math
DEBUG_CFLAGS = -Wall -Werror -m486 -g -DDEBUGMODE=1
RELEASE_LFLAGS = -s `allegro-config --libs`
DEBUG_LFLAGS = -g `allegro-config --static debug`

include makefile.all
